
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company?serverTimezone=Asia/Taipei&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: GMT+8


#logging.level.org.hibernate:
#  SQL: DEBUG
#  type.descriptor.sql: TRACE


